In [3]:
# pandas를 활용한 데이터 전처리

import pandas as pd

temp = pd.Series([-20, -10, 10, 20])   # 시리즈
temp

0   -20
1   -10
2    10
3    20
dtype: int64

In [6]:
import pandas as pd

# 인덱스 이름 변경 가능
temp = pd.Series([-20, -10, 10, 20], index=['Jan', 'Feb', 'Mar', 'Apr'])
temp['Mar']   # 변경된 인덱스 이름으로 접근 가능

np.int64(10)

In [10]:
import pandas as pd

# dictionary
data = data = {
    '이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키': [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어': [85, 35, 75, 60, 20, 100, 65, 85],
    '수학': [100, 50, 70, 70, 10, 95, 45, 90],
    '과학': [95, 55, 80, 75, 35, 85, 40, 95],
    '사회': [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data)   # data를 2차원의 데이터프레임 df로 만듦

df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197   90   85  100  95  85      Python
1  정대만  북산고  184   40   35   50  55  25        Java
2  송태섭  북산고  168   80   75   70  80  75  Javascript
3  서태웅  북산고  187   40   60   70  75  80
4  강백호  북산고  188   15   20   10  35  10
5  변덕규  능남고  202   80  100   95  85  80           C
6  황태산  능남고  188   55   65   45  40  35      PYTHON
7  윤대협  능남고  190  100   85   90  95  95          C#

In [11]:
df['이름']   # 특정 컬럼 데이터 보고 싶을 때

0    채치수
1    정대만
2    송태섭
3    서태웅
4    강백호
5    변덕규
6    황태산
7    윤대협
Name: 이름, dtype: str

In [12]:
df[['이름', '키']]   # 복수 컬럼의 경우 대괄호 2개!

    이름    키
0  채치수  197
1  정대만  184
2  송태섭  168
3  서태웅  187
4  강백호  188
5  변덕규  202
6  황태산  188
7  윤대협  190

In [13]:
# 리스트도 2차원 가능
lst = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [35]:
import pandas as pd

# dictionary
data = data = {
    '이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키': [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어': [85, 35, 75, 60, 20, 100, 65, 85],
    '수학': [100, 50, 70, 70, 10, 95, 45, 90],
    '과학': [95, 55, 80, 75, 35, 85, 40, 95],
    '사회': [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

# 인덱스 지정 가능
df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'])

df

     이름   학교    키   국어   영어   수학  과학  사회        SW특기
1번  채치수  북산고  197   90   85  100  95  85      Python
2번  정대만  북산고  184   40   35   50  55  25        Java
3번  송태섭  북산고  168   80   75   70  80  75  Javascript
4번  서태웅  북산고  187   40   60   70  75  80
5번  강백호  북산고  188   15   20   10  35  10
6번  변덕규  능남고  202   80  100   95  85  80           C
7번  황태산  능남고  188   55   65   45  40  35      PYTHON
8번  윤대협  능남고  190  100   85   90  95  95          C#

In [15]:
# 원하는 컬럼으로만 데이터프레임 지정 가능

df = pd.DataFrame(data, columns=['이름', '학교', '키'])

df

    이름   학교    키
0  채치수  북산고  197
1  정대만  북산고  184
2  송태섭  북산고  168
3  서태웅  북산고  187
4  강백호  북산고  188
5  변덕규  능남고  202
6  황태산  능남고  188
7  윤대협  능남고  190

In [27]:
# 인덱스 이름 지정 가능


df.index.name = '지원번호'

df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [28]:
# 인덱스 이름 초기화 가능

df = df.reset_index(drop=True)   # 인덱스로 정의한 것을 제거하고 원래대로 초기화
# df.reset_index(drop=True, inplace=True)

df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197   90   85  100  95  85      Python
1  정대만  북산고  184   40   35   50  55  25        Java
2  송태섭  북산고  168   80   75   70  80  75  Javascript
3  서태웅  북산고  187   40   60   70  75  80
4  강백호  북산고  188   15   20   10  35  10
5  변덕규  능남고  202   80  100   95  85  80           C
6  황태산  능남고  188   55   65   45  40  35      PYTHON
7  윤대협  능남고  190  100   85   90  95  95          C#

In [29]:
# 컬럼을 인덱스로 지정 가능

df.set_index('이름')

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
채치수  북산고  197   90   85  100  95  85      Python
정대만  북산고  184   40   35   50  55  25        Java
송태섭  북산고  168   80   75   70  80  75  Javascript
서태웅  북산고  187   40   60   70  75  80
강백호  북산고  188   15   20   10  35  10
변덕규  능남고  202   80  100   95  85  80           C
황태산  능남고  188   55   65   45  40  35      PYTHON
윤대협  능남고  190  100   85   90  95  95          C#

In [34]:
# 원본 데이터는 그대로임

df

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
채치수  북산고  197   90   85  100  95  85      Python
정대만  북산고  184   40   35   50  55  25        Java
송태섭  북산고  168   80   75   70  80  75  Javascript
서태웅  북산고  187   40   60   70  75  80
강백호  북산고  188   15   20   10  35  10
변덕규  능남고  202   80  100   95  85  80           C
황태산  능남고  188   55   65   45  40  35      PYTHON
윤대협  능남고  190  100   85   90  95  95          C#

In [36]:
# 원본 데이터도 바꾸고 싶을 때

df.set_index('이름', inplace = True)

df

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
채치수  북산고  197   90   85  100  95  85      Python
정대만  북산고  184   40   35   50  55  25        Java
송태섭  북산고  168   80   75   70  80  75  Javascript
서태웅  북산고  187   40   60   70  75  80
강백호  북산고  188   15   20   10  35  10
변덕규  능남고  202   80  100   95  85  80           C
황태산  능남고  188   55   65   45  40  35      PYTHON
윤대협  능남고  190  100   85   90  95  95          C#

In [38]:
# 오름차순 / 내림차순

df.sort_index()   # 기본값: 오름차순
df.sort_index(ascending=False)   # 내림차순

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
황태산  능남고  188   55   65   45  40  35      PYTHON
채치수  북산고  197   90   85  100  95  85      Python
정대만  북산고  184   40   35   50  55  25        Java
윤대협  능남고  190  100   85   90  95  95          C#
송태섭  북산고  168   80   75   70  80  75  Javascript
서태웅  북산고  187   40   60   70  75  80
변덕규  능남고  202   80  100   95  85  80           C
강백호  북산고  188   15   20   10  35  10

In [39]:
print(df.columns)

Index(['학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [41]:
# csv 파일 열기
# pd.read_csv()

import pandas as pd

df_test = pd.read_csv('test.csv')
df_test

,title,link,date,content
0,서울 이태원 데이트 수제버거 맛집 다운타우너 한남 방문 후기 메뉴 추천,https://blog.naver.com/believe1us/224305395055,2026. 6. 4.,서울 이태원 데이트 수제버거 맛집 다운타우너 한남 방문 후기 메뉴 추천​서울 이태원...
1,다운타우너 버거 한남동 수제버거 맛집,https://blog.naver.com/johan0626/224306024823,2026. 6. 4.,다운타우너 버거 한남동 수제버거 맛집한남동 수제버거​이태원 빙수 먹으러 갔던 날 사...
2,[서울] 가성비 버거맛집! 다양한 햄버거와 치킨이 있는 수제버거집 <프레디버거 서울...,https://blog.naver.com/tig04180/224283389118,2026. 5. 12.,[서울] 가성비 버거맛집! 다양한 햄버거와 치킨이 있는 수제버거집 <프레디버거 서울...
3,파이브 가이즈 여의도 더현대서울 지하 햄버거 맛집,https://blog.naver.com/mandoozip22/224297251232,2026. 5. 26.,파이브 가이즈 여의도 더현대서울 지하 햄버거 맛집하루종일 든든한 수제 햄버거파이브가...
4,"[서울역 맛집] 파이브가이즈 서울역점 내돈내산 솔직 후기, 혼밥하기 좋은 햄버거집",https://blog.naver.com/byeunny_/224251133613,2026. 4. 13.,"[서울역 맛집] 파이브가이즈 서울역점 내돈내산 솔직 후기, 혼밥하기 좋은 햄버거집안..."
5,서울 햄버거 맛집 파이브가이즈 강남 미국 본토의 맛 가득,https://blog.naver.com/ahn-1113/224164796956,2026. 2. 3.,서울 햄버거 맛집 파이브가이즈 강남 미국 본토의 맛 가득안녕하세요.블로그 주인장 먹...
6,"서울 광화문 수제버거 맛집 다운타우너｜아보카도버거 혼밥 추천, 직장인 점심 맛집",https://blog.naver.com/gsw03169/224307869377,2026. 6. 6.,"서울 광화문 수제버거 맛집 다운타우너｜아보카도버거 혼밥 추천, 직장인 점심 맛집​광..."

In [43]:
# csv로 저장하기
# df.to_csv('score.csv', encoding='utf-8-sig', index=False)

import pandas as pd

# dictionary
data = data = {
    '이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키': [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어': [85, 35, 75, 60, 20, 100, 65, 85],
    '수학': [100, 50, 70, 70, 10, 95, 45, 90],
    '과학': [95, 55, 80, 75, 35, 85, 40, 95],
    '사회': [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data)

df.to_csv('score.csv', encoding='utf-8-sig', index=False)   # 인덱스 제외
# 엑셀 사용 시 utf-8-sig 필수!

In [45]:
import pandas as pd

df = pd.read_csv('score.csv')
df.describe()   # 수치만 계산 가능

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 708.0 bytes

In [48]:
df.head()   # 상위 5개 보여줌 (기본값 5)

    이름   학교    키  국어  영어   수학  과학  사회        SW특기
0  채치수  북산고  197  90  85  100  95  85      Python
1  정대만  북산고  184  40  35   50  55  25        Java
2  송태섭  북산고  168  80  75   70  80  75  Javascript
3  서태웅  북산고  187  40  60   70  75  80         NaN
4  강백호  북산고  188  15  20   10  35  10         NaN

In [49]:
df.head(7)   # 확인하고자 하는 데이터 수 변경 가능

    이름   학교    키  국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197  90   85  100  95  85      Python
1  정대만  북산고  184  40   35   50  55  25        Java
2  송태섭  북산고  168  80   75   70  80  75  Javascript
3  서태웅  북산고  187  40   60   70  75  80         NaN
4  강백호  북산고  188  15   20   10  35  10         NaN
5  변덕규  능남고  202  80  100   95  85  80           C
6  황태산  능남고  188  55   65   45  40  35      PYTHON

In [50]:
df.tail()   # 뒤에서부터 괄호 안 숫자 개수까지 확인 가능 (기본값: 5)

    이름   학교    키   국어   영어  수학  과학  사회    SW특기
3  서태웅  북산고  187   40   60  70  75  80     NaN
4  강백호  북산고  188   15   20  10  35  10     NaN
5  변덕규  능남고  202   80  100  95  85  80       C
6  황태산  능남고  188   55   65  45  40  35  PYTHON
7  윤대협  능남고  190  100   85  90  95  95      C#

In [52]:
df.values

array([['채치수', '북산고', 197, 90, 85, 100, 95, 85, 'Python'],
       ['정대만', '북산고', 184, 40, 35, 50, 55, 25, 'Java'],
       ['송태섭', '북산고', 168, 80, 75, 70, 80, 75, 'Javascript'],
       ['서태웅', '북산고', 187, 40, 60, 70, 75, 80, nan],
       ['강백호', '북산고', 188, 15, 20, 10, 35, 10, nan],
       ['변덕규', '능남고', 202, 80, 100, 95, 85, 80, 'C'],
       ['황태산', '능남고', 188, 55, 65, 45, 40, 35, 'PYTHON'],
       ['윤대협', '능남고', 190, 100, 85, 90, 95, 95, 'C#']], dtype=object)

In [53]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [55]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [56]:
df['이름'].count()

np.int64(8)

In [58]:
df['키'].max()

np.int64(202)

In [59]:
df['국어'].sum()

np.int64(500)

In [60]:
# count 시 빈 값은 개수 세지 않음!
df['SW특기'].count()

np.int64(6)

In [61]:
# .unique()  데이터 중복을 제거하고 출력
df['학교'].unique()

<StringArray>
['북산고', '능남고']
Length: 2, dtype: str

In [62]:
# .nunique()  데이터 중복을 제거하고 유니크한 값 개수 출력
df['학교'].nunique()

2

In [63]:
import pandas as pd

df = pd.read_csv('score.csv')
df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197   90   85  100  95  85      Python
1  정대만  북산고  184   40   35   50  55  25        Java
2  송태섭  북산고  168   80   75   70  80  75  Javascript
3  서태웅  북산고  187   40   60   70  75  80         NaN
4  강백호  북산고  188   15   20   10  35  10         NaN
5  변덕규  능남고  202   80  100   95  85  80           C
6  황태산  능남고  188   55   65   45  40  35      PYTHON
7  윤대협  능남고  190  100   85   90  95  95          C#

In [64]:
df[['이름', '키']]

    이름    키
0  채치수  197
1  정대만  184
2  송태섭  168
3  서태웅  187
4  강백호  188
5  변덕규  202
6  황태산  188
7  윤대협  190

In [65]:
# 컬럼 이름 모를 때 순서로 확인 가능
df.columns[0]

'이름'

In [66]:
# 컬럼의 순서를 알면 아래 방식으로 확인 가능
df[df.columns[0]]

0    채치수
1    정대만
2    송태섭
3    서태웅
4    강백호
5    변덕규
6    황태산
7    윤대협
Name: 이름, dtype: str

In [67]:
# 뒤쪽부터 셀 수 있음
df.columns[-1]

'SW특기'

In [68]:
df[df.columns[-1]]

0        Python
1          Java
2    Javascript
3           NaN
4           NaN
5             C
6        PYTHON
7            C#
Name: SW특기, dtype: str

In [69]:
import pandas as pd

df = pd.read_csv('score.csv')
df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197   90   85  100  95  85      Python
1  정대만  북산고  184   40   35   50  55  25        Java
2  송태섭  북산고  168   80   75   70  80  75  Javascript
3  서태웅  북산고  187   40   60   70  75  80         NaN
4  강백호  북산고  188   15   20   10  35  10         NaN
5  변덕규  능남고  202   80  100   95  85  80           C
6  황태산  능남고  188   55   65   45  40  35      PYTHON
7  윤대협  능남고  190  100   85   90  95  95          C#

In [70]:
# 컬럼 기준 슬라이싱!
# 특정 행열 선택 [컬럼][행 범위]
df['영어'][0:5]

0    85
1    35
2    75
3    60
4    20
Name: 영어, dtype: int64

In [71]:
df[['이름', '영어']][0:5]

    이름  영어
0  채치수  85
1  정대만  35
2  송태섭  75
3  서태웅  60
4  강백호  20

In [72]:
df[['이름', '영어']][3:]

    이름   영어
3  서태웅   60
4  강백호   20
5  변덕규  100
6  황태산   65
7  윤대협   85

In [73]:
lst = [1,2,3,4,5,6,7]
lst[3:]

[4, 5, 6, 7]

In [74]:
import pandas as pd

# dictionary
data = data = {
    '이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키': [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어': [85, 35, 75, 60, 20, 100, 65, 85],
    '수학': [100, 50, 70, 70, 10, 95, 45, 90],
    '과학': [95, 55, 80, 75, 35, 85, 40, 95],
    '사회': [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

# 인덱스 지정 가능
df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'])
df.index.name = '지원번호'

df.to_csv('score.csv', encoding='utf-8-sig', index = True)

In [75]:
df = pd.read_csv('score.csv', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [76]:
# 행 기준 슬라이싱!
# loc : 자신이 만든 인덱스 이름으로 선택할 때

df.loc['1번']

이름         채치수
학교         북산고
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    Python
Name: 1번, dtype: object

In [77]:
df.loc['5번']

이름      강백호
학교      북산고
키       188
국어       15
영어       20
수학       10
과학       35
사회       10
SW특기    NaN
Name: 5번, dtype: object

In [78]:
df.loc['1번', '국어']

np.int64(90)

In [79]:
df.loc[['1번', '2번'], '국어']

지원번호
1번    90
2번    40
Name: 국어, dtype: int64

In [81]:
# 여러 개 선택할 때는 대괄호 2번!

df.loc[['1번', '2번'], ['국어', '수학']]

      국어   수학
지원번호
1번    90  100
2번    40   50

In [86]:
# 범위 지정 가능 - 대괄호 1번!
# loc 주로 문자 인덱스일 때 사용

df.loc['1번':'5번', '국어': '수학']

      국어  영어   수학
지원번호
1번    90  85  100
2번    40  35   50
3번    80  75   70
4번    40  60   70
5번    15  20   10