In [11]:
import pandas as pd

# csv 파일 불러오기
df= pd.read_csv('score.csv')

# excel 파일로 저장하기
df.to_excel('score.xlsx',index = False)

In [36]:
df = pd.read_excel('score.xlsx', index_col = '지원번호')   # '지원번호' 열을 인덱스(행의 이름표)로 사용
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [10]:
# 데이터 선택 loc : 문자 형태의 인덱스, 컬럼명

df.loc['1번', '국어']

df.loc[['1번', '2번'], ['국어', '영어']]   # df.loc[ 행 , 열 ]

df.loc['1번':'5번', '국어':'수학']   # 범위 지정 가능

      국어  영어   수학
지원번호
1번    90  85  100
2번    40  35   50
3번    80  75   70
4번    40  60   70
5번    15  20   10

In [32]:
df = pd.read_excel('score.xlsx', index_col = '지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [13]:
# 숫자 인덱스 : iloc (integer 정수) - 몇 번째 인덱스인지 특정

df.iloc[4]

이름      강백호
학교      북산고
키       188
국어       15
영어       20
수학       10
과학       35
사회       10
SW특기    NaN
Name: 5번, dtype: object

In [14]:
df.iloc[0:4]   # 슬라이싱 가능

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python
2번    정대만  북산고  184  40  35   50  55  25        Java
3번    송태섭  북산고  168  80  75   70  80  75  Javascript
4번    서태웅  북산고  187  40  60   70  75  80         NaN

In [15]:
df.iloc[0,1]

'북산고'

In [16]:
# 0번째 행과 2번째 행, 그리고 1번째 열과 3번째 열의 데이터만 가져오기
df.iloc[[0, 2], [1, 3]]

       학교  국어
지원번호
1번    북산고  90
3번    북산고  80

In [17]:
# 0번째부터 2번째(3은 제외) 행, 1번째부터 3번째(4는 제외) 열까지 가져오기
df.iloc[0:3, 1:4]

       학교    키  국어
지원번호
1번    북산고  197  90
2번    북산고  184  40
3번    북산고  168  80

In [18]:
filt = df['키'] >= 185
df[filt]

# 한 줄로 작성 가능: df[df['키'] >= 185]

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
4번    서태웅  북산고  187   40   60   70  75  80     NaN
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
7번    황태산  능남고  188   55   65   45  40  35  PYTHON
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [19]:
# 조건에 해당하지 않는 값들만 보기
df[~filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [20]:
# 조건부 필터링
# 조건: 키가 185 이상인 행만 / 열: 그 중에서 '수학' 점수 열만 선택
df.loc[df['키'] >= 185, '수학']

지원번호
1번    100
4번     70
5번     10
6번     95
7번     45
8번     90
Name: 수학, dtype: int64

# df.loc[조건, 보고 싶은 정보]
# 다중 조건부 필터링

In [21]:
# and 조건
df.loc[(df['키'] >= 185) & (df['학교']=='북산고'), ['수학', '영어']]

       수학  영어
지원번호
1번    100  85
4번     70  60
5번     10  20

In [22]:
# or 조건
df.loc[(df['키'] < 170) | (df['키'] > 200), ['수학', '과학']]

      수학  과학
지원번호
3번    70  80
6번    95  85

In [23]:
# 데이터 소문자로 바꾸기

# 'SW특기' 열에 있는 모든 문자열 데이터를 소문자로 바꿈
df['SW특기'].str.lower()

지원번호
1번        python
2번          java
3번    javascript
4번           NaN
5번           NaN
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

# 문자열로 비교해서 검색

In [24]:
lang = ['java']

# "SW특기 열의 값을 소문자로 바꾼 뒤, lang이라는 리스트 안에 포함되어 있는지 확인
df['SW특기'].str.lower().isin(lang)

지원번호
1번    False
2번     True
3번    False
4번    False
5번    False
6번    False
7번    False
8번    False
Name: SW특기, dtype: bool

In [25]:
# 'SW특기' 열에서 'Java'라는 글자가 포함된 데이터를 찾아 True/False로 반환

df['SW특기'].str.contains('Java')

지원번호
1번    False
2번     True
3번     True
4번    False
5번    False
6번    False
7번    False
8번    False
Name: SW특기, dtype: bool

In [26]:
# "SW특기 열에 'Java'가 포함된 데이터를 찾되, 비어있는 값(NaN)은 True로 처리
df['SW특기'].str.contains('Java', na=True)

지원번호
1번    False
2번     True
3번     True
4번     True
5번     True
6번    False
7번    False
8번    False
Name: SW특기, dtype: bool

In [27]:
# 'SW특기' 열에 'Java'라는 글자가 포함된 행만 필터링하여 데이터를 추출

filt = df['SW특기'].str.contains('Java')
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [28]:
# 결측치 처리

# 결측치 있는 데이터 삭제
df.dropna()

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [29]:
# 데이터 그대로 살아있음
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [30]:
# 반영시키는 방법 (1) inplace=True   (2) 데이터프레임으로 저장
# 행 전체 삭제

df.dropna(inplace = True)
# 또는
df = df.dropna()

In [31]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [ ]:
# axis = index, columns   기준을 설정
# how = any, all
   # any: 한 개라도 있으면 삭제
   # all: 전부 na이면 삭제

In [33]:
# 데이터프레임 내에 하나라도 결측치(NaN, 비어있는 값)가 포함된 모든 열(Column)을 삭제
# axis='columns': 행이 아니라 '열'을 기준으로 삭제 (axis=1 과 동일)

df.dropna(axis = 'columns')

       이름   학교    키   국어   영어   수학  과학  사회
지원번호
1번    채치수  북산고  197   90   85  100  95  85
2번    정대만  북산고  184   40   35   50  55  25
3번    송태섭  북산고  168   80   75   70  80  75
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80
7번    황태산  능남고  188   55   65   45  40  35
8번    윤대협  능남고  190  100   85   90  95  95

In [35]:
# 데이터프레임에서 결측치(NaN)가 하나라도 포함된 '행'을 모두 삭wp
# axis='index': 행(Row)을 기준으로 삭제 (기본값이므로 생략해도 동일하게 동작하며, axis=0과 동일)

df.dropna(axis='index', how = 'any')

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [37]:
# 데이터프레임에서 모든 열의 값이 비어있는(NaN) 행만 삭제

df.dropna(axis='index', how = 'all')

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [38]:
import numpy as np

df['학교'] = np.nan
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [39]:
df.dropna(axis='index', how = 'all')

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [40]:
df = pd.read_excel('score.xlsx', index_col = '지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [41]:
# 정렬

# 기본: 오름차순
df.sort_values('키')

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
2번    정대만  북산고  184   40   35   50  55  25        Java
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#
1번    채치수  북산고  197   90   85  100  95  85      Python
6번    변덕규  능남고  202   80  100   95  85  80           C

In [42]:
# 내림차순

df.sort_values('키', ascending = False)

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
6번    변덕규  능남고  202   80  100   95  85  80           C
1번    채치수  북산고  197   90   85  100  95  85      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
4번    서태웅  북산고  187   40   60   70  75  80         NaN
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript

In [43]:
# '학교' 열에 있는 '북산고'라는 값을 모두 찾아서 '상북고'로 바꿈
df['학교'].replace({'북산고':'상북고'})

지원번호
1번    상북고
2번    상북고
3번    상북고
4번    상북고
5번    상북고
6번    능남고
7번    능남고
8번    능남고
Name: 학교, dtype: str

In [44]:
text = 'abcd'
text = text.capitalize()   # 문자열의 첫 번째 글자는 대문자로, 나머지 글자는 모두 소문자로 변환

text

'Abcd'

In [48]:
# 함수 작성

def Low(str):   # 입력받은 문자열을 소문자로 바꾸는 함수 정의
    if pd.isna(str):   # 입력값이 결측치(NaN)인지 확인
        return str     # 결측치라면 변환하지 않고 그대로 반환
    else:   # 결측치가 아니라면
        result = str.lower()   # 문자열을 소문자로 변환하여 result에 저장
        return result   # 변환된 결과 반환

df['SW특기'].apply(Low)  # 'SW특기' 열의 각 데이터마다 Low 함수를 적용

지원번호
1번        python
2번          java
3번    javascript
4번           NaN
5번           NaN
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

# 네이버 블로그 [서울 버거 맛집] 웹크롤링 데이터 약 200개 - 데이터전처리

In [ ]:
# csv로 저장된 파일 열기

import pandas as pd

df= pd.read_csv('서울_버거_맛집_200.csv')

df.head(50)

In [ ]:
# 가. 정규식을 사용하여 데이터 전처리

r'...': 파이썬에서 정규표현식을 사용할 때 쓰는 'raw string' 형식
[^...]: ^는 "이 안에 있는 것들이 아닌 것"을 찾겠다
a-zA-Z0-9가-힣: 영어 소문자, 대문자, 숫자, 한글 전체를 의미
' ' (공백): 만약 공백까지 살리고 싶다면 꼭 포함
'': 찾은 특수문자들을 빈 문자열로 치환(제거)
regex=True: 정규표현식을 사용하겠다는 설정

In [ ]:
# 가-1. 'title' 컬럼의 특수문자 제거 (정규식 활용)
    # [^a-zA-Z0-9가-힣 ] : 영어, 숫자, 한글, 공백이 아닌 모든 것을 찾음

df['title'] = df['title'].str.replace(r'[^a-zA-Z0-9가-힣 ]', '', regex=True)

df.head(10)

1. '2026.06', '2026-06' 등 숫자와 기호로 된 날짜 제거
df['title'] = df['title'].str.replace(r'\d{2,4}[-./]\d{1,2}', '', regex=True)

2. '2026년 6월', '2026년 06월' 등 한글이 포함된 날짜 제거
df['title'] = df['title'].str.replace(r'\d{4}년\s?\d{1,2}월', '', regex=True)

In [54]:
# 가-2. 연도/월 등 날짜가 있는 경우 제거

df['title'] = df['title'].str.replace(r'\d{2,4}[-./]\d{1,2}', '', regex=True)
df['title'] = df['title'].str.replace(r'\d{4}년\s?\d{1,2}월', '', regex=True)

In [ ]:
df.iloc[100:150]

# 나. 표준화

In [56]:
# 나-1. 영문자를 모두 소문자로 변경

# 'title' 컬럼의 모든 대문자를 소문자로 변환
df['title'] = df['title'].str.lower()

In [ ]:
# (option) 영문자 모두 제거하고 싶은 경우

# 1. 영문자 제거
df['title'] = df['title'].str.replace(r'[a-zA-Z]', '', regex=True)

# 2. 제거 후 남은 불필요한 앞뒤 공백 제거
df['title'] = df['title'].str.strip()

# 3. 만약 중간에 남은 다중 공백을 하나로 줄이고 싶다면
df['title'] = df['title'].str.replace(r'\s+', ' ', regex=True)

# 다. 데이터 가공

In [ ]:
# 다-1. title, content에 데이터가 없으면 삭제

In [ ]:
# 'title' 또는 'content' 컬럼에 NaN이 있는 행 삭제
df.dropna(subset=['title', 'content'], how='any', inplace=True)

In [ ]:
# 둘 다 비어있을 때만 삭제하고 싶을 때
df.dropna(subset=['title', 'content'], how='all', inplace=True)

In [57]:
# 삭제된 데이터(행)가 몇 개인지 알고 싶을 때

print("삭제 전 행 개수:", len(df))
df.dropna(subset=['title', 'content'], how='all', inplace=True)
print("삭제 후 행 개수:", len(df))

삭제 전 행 개수: 203
삭제 후 행 개수: 203

In [59]:
# 다-2. title 데이터가 중복인 경우

# 'title' 컬럼을 기준으로 중복된 행을 삭제 (첫 번째 항목만 남기고 나머지는 삭제)
df.drop_duplicates(subset=['title'], inplace=True)
print("삭제 후 행 개수:", len(df))

삭제 후 행 개수: 202

# 라. 기타 데이터 제거

In [64]:
# 라-1. 서울이 아닌 지역 있으면 행 제거
    # title 컬럼에 제주, 부산, 과천, 괌, 양평이 있는지 확인

filt = df['title'].str.contains('제주')

df = df[~df['title'].str.contains('과천|제주|부산|괌|양평', na=False)]
print("삭제 후 행 개수:", len(df))

# df['포함여부'] = df['title'].str.contains('|'.join(['제주', '부산', '과천', '괌']), na=False)

삭제 후 행 개수: 197

In [66]:
# 라-2. 불용어(stopword) 제거

# 1. 제거할 단어 리스트 정의
stop_words = ['에서', '까지', '와', '과', '의', '로', '은', '는', '이', '가']

# 2. 리스트를 '|'로 연결하여 정규표현식 패턴 생성
pattern = r'\b(' + '|'.join(stop_words) + r')\b'

# 3. 패턴 적용하여 단어 삭제
df['title'] = df['title'].str.replace(pattern, '', regex=True).str.strip()

In [67]:
# 라-3. 연속된 공백 제거

df['title'] = df['title'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [ ]:
df.iloc[0:50]

# link 주소에서 마지막 숫자를 post_id로 추출하여 컬럼 저장

In [69]:
# 마지막 슬래시(/) 뒤에 있는 고유 ID만 뽑아내어 새로운 컬럼을 만듦

df['post_id'] = df['link'].str.split('/').str[-1]

In [72]:
# 데이터 중간 저장

output_file = '서울_버거_맛집_200_전처리_1.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print('CSV_전처리_1 파일 저장 완료')

CSV_전처리_1 파일 저장 완료

# NLTK 모듈 활용

In [74]:
import nltk

# 리소스 다운로드
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')   # 불용어

# 샘플 문장
sp_sentence = 'The quick brown fox jumped over the lazy dog.'
words = nltk.word_tokenize(sp_sentence)

for word in words:
    print(word)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/garyungkim/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/garyungkim/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/garyungkim/nltk_data...

The
quick
brown
fox
jumped
over
the
lazy
dog
.

[nltk_data]   Unzipping corpora/stopwords.zip.

In [75]:
# 품사 태깅
nltk.download('averaged_perceptron_tagger_eng')
tags = nltk.pos_tag(words)

for tag in tags:
    print(tag)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/garyungkim/nltk_data...

('The', 'DT')
('quick', 'JJ')
('brown', 'NN')
('fox', 'NN')
('jumped', 'VBD')
('over', 'IN')
('the', 'DT')
('lazy', 'JJ')
('dog', 'NN')
('.', '.')

[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

In [77]:
# 불용어 제거

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords') 
stop_words = set(stopwords.words('english'))
new_words = [word for word in words if word not in stop_words]

for new_word in new_words:
    print(new_word)

The
quick
brown
fox
jumped
lazy
dog
.

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/garyungkim/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

# konlpy 활용
자바 기반이므로 JDK (자바가상머신)이 설치되어야 함!

In [78]:
from konlpy.tag import Okt